#!/usr/local/bin/perl
#
# build-docs - construct the SGML docbook files from the parts
#
# $Id$
#
# Copyright (C) 2000-2004, David Beckett http://purl.org/net/dajobe/
# Institute for Learning and Research Technology http://www.ilrt.bristol.ac.uk/
# University of Bristol, UK http://www.bristol.ac.uk/
# 
# This package is Free Software and part of Redland http://librdf.org/
# 
# It is licensed under the following three licenses as alternatives:
#   1. GNU Lesser General Public License (LGPL) V2.1 or any newer version
#   2. GNU General Public License (GPL) V2 or any newer version
#   3. Apache License, V2.0 or any newer version
# 
# You may not use this file except in compliance with at least one of
# the above three licenses.
# 
# See LICENSE.html or LICENSE.txt at the top of this package for the
# complete terms and further detail along with the license texts for
# the licenses in COPYING.LIB, COPYING and LICENSE-2.0.txt respectively.
# 
# 


$::verbose=0;

my($prototype)=@ARGV;


open(PROTO, $prototype) or die "Cannot open $prototype - $!\n";
while(<PROTO>) {
  if(/^\@INCLUDE\s+(.+)$/) {
    my $file=$1;
    my $content='';
    open(IN, $file) or die "$prototype:$.: Cannot open $file - $!\n";
    while(<IN>) {
      # Try to shorten SGML ids - otherwise jade moans
      s/id="API-librdf-/id="/;

      # kernel-doc doesn't seem to get this right - why?
      s%\&amp;((struct\s*)?\w+)%<structname>$1</structname>%g;
      $content.=$_;
    }
    close(IN);
    print $content;
    next;
  }
  print;
}
