#!/usr/local/bin/perl
#
# build-docs - construct the SGML docbook files from the parts
#
# $Id$
#
# Copyright (C) 2000-2001 David Beckett - http://purl.org/net/dajobe/
# Institute for Learning and Research Technology - http://www.ilrt.org/
# University of Bristol - http://www.bristol.ac.uk/
# 
# This package is Free Software or Open Source available under the
# following licenses (these are alternatives):
#   1. GNU Lesser General Public License (LGPL) Version 2
#   2. GNU General Public License (GPL) Version 2
#   3. Mozilla Public License (MPL) Version 1.1
# and no other versions of those licenses.
# 
# See INSTALL.html or INSTALL.txt at the top of this package for the
# full license terms.
# 


$::verbose=0;

my($prototype)=@ARGV;


open(PROTO, $prototype) or die "Cannot open $prototype - $!\n";
while(<PROTO>) {
  if(/^\@INCLUDE\s+(.+)$/) {
    my $file=$1;
    my $content='';
    open(IN, $file) or die "$prototype:$.: Cannot open $file - $!\n";
    while(<IN>) {
      # Try to shorten SGML ids - otherwise jade moans
      s/id="API-librdf-/id="/;

      # kernel-doc doesn't seem to get this right - why?
      s%\&amp;((struct\s*)?\w+)%<structname>$1</structname>%g;
      $content.=$_;
    }
    close(IN);
    print $content;
    next;
  }
  print;
}
