#!/usr/bin/perl

my $main_title="Redland RDF Application Framework";

my $doc_title;

while(<>) {
  $doc_title=$1 if s%<title>(.*?)</title>%<title>$main_title - $1</title>%;

  s%<h1>%<h2>%; s%</h1>%</h2>%;
  s%<hr />%%;

  s%^<body>%<body bgcolor="#ffffff" text="#000085">\n\n<h1 align="center">$main_title - $doc_title</h1>\n\n%;

  print <<"EOT" if m%^</body>%;
<hr />

<p>Copyright 2001 <a href="http://purl.org/net/dajobe/">Dave Beckett</a>, <a href="http://www.ilrt.bristol.ac.uk/">Institute for Learning and Research Technology</a>, <a href="http://www.bristol.ac.uk/">University of Bristol</a></p>

<p><a href="http://www.mirror.ac.uk/services/validator/check/referer">Validate me</a></p>
EOT
  print unless /^<link|meta/;
}
